version: '3.7'
services:
  app:
    build:
      context: Dockerfile.d/
      dockerfile: app.Dockerfile
      target: development
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
    ports:
      - '${BIND_IP_ADDR:-127.0.0.1}:3000:3000'
    user: '${UID:-0}:${GID:-0}'
    environment:
      - SSH_AUTH_SOCK
    command: sleep infinity
